### ISSUE TITLE
Question: Where does the syntax <Probe /> and so on does come from

### ISSUE THREAD

**Issue by frank-dspeed** [hpi-swa/polyglot-live-programming#13]
Hello i wonder where the xml like syntax is defined as i would love to offer Alternativ one for JS live coding only.

In ECMAScript we use already a convention we call it JSDOC i would love to create a compatible syntax that can get used in .js files.

**Comment by fniephaus** [comment]
Hi Frank, thanks for the question.
The XML-like syntax is currently defined in the `BabylonianAnalysisExtension.java` and it uses a Java `DocumentBuilder` for XML parsing:
https://github.com/hpi-swa/polyglot-live-programming/blob/f85082d917fe63f73057a9512a9b5064003de3b6/src/de.hpi.swa.liveprogramming/src/de/hpi/swa/liveprogramming/BabylonianAnalysisExtension.java#L159-L170

As part of this project, we mainly focused on live programming aspects and not so much on designing a nice meta-language for defining examples. Any ideas are therefore welcome!
